---
- name: Install nginx
  hosts: web
  tasks:
   - name: Installing nginx package
     ansible.builtin.package:
      name: nginx
      state: installed

    - name: Start service
      ansible.builtin.service:
       name: nginx
       state: started
       enabled: yes
...