---
- name: Install nginx
  hosts: web
  become: yes
  tasks:
   - name: Installing nginx package
     ansible.builtin.package:
      name: nginx
      state: installed

   - name: start service
     ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
...