- name: demo on conditions
  hosts: local
  connection: local
  vars:
   IS_LIVE: true
  tasks:
   - name: check live or not 
     ansible.builtin.debug:
      msg: "Yes,It is live"
     when: IS_LIVE