- name: Install the packages 
  hosts: local
  become: yes
  connection: local
  tasks:
   - name: Install packages with help of loops 
     ansible.builtin.package:
      name: "{{item}}"
      state: present
     loop:
      - mysql
      - nginx 
      - zip